---
- name: Git管理下から除外するファイルの設定を追加
  ansible.builtin.blockinfile:
    path: "{{ base_dir }}/.gitignore"
    content: |
      /.editorconfig
      /.envrc
      /.erdconfig
      /.vscode/
      /.yardoc/
      /doc/app/
      /doc/assets/
      /doc/schema/
  register: gitignore_result
- name: .gitignoreの変更を無視するように設定
  ansible.builtin.command:
    cmd: git update-index --skip-worktree .gitignore
    chdir: "{{ base_dir }}"
  when: gitignore_result is changed
