---
- name: mycliのインストール
  community.general.pipx:
    name: mycli
    state: install
    install_deps: true
- name: mycliの設定ファイルをコピー
  ansible.builtin.copy:
    src: myclirc
    dest: ~/.myclirc
    mode: "0644"
