---
- name: Set Install version variable
  when: pandoc_version | default('latest') == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_reauest_header) }}"
      vars:
        merge_reauest_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/jgm/pandoc/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: Set version variable
      ansible.builtin.set_fact:
        pandoc_version: "{{ latest_releases.json.tag_name }}"
- name: Install pandoc
  ansible.builtin.apt:
    deb: https://github.com/jgm/pandoc/releases/download/{{ pandoc_version }}/pandoc-{{ pandoc_version }}-1-amd64.deb
