production:
  adapter: mysql2
  database: app_prod
  host: mariadb
  username: app_prod
  password: app_prod_password
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
development:
  adapter: mysql2
  database: app_dev
  host: mariadb
  username: app_dev
  password: app_dev_password
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
test:
  adapter: mysql2
  database: app_test
  host: mariadb
  username: app_test
  password: app_test_password
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4

