---
- name: bundlerの設定ファイル格納ディレクトリを作成
  ansible.builtin.file:
    path: "{{ playbook_dir | dirname }}/.bundle"
    state: directory
    mode: "0755"
- name: bundlerの設定ファイルをコピー
  ansible.builtin.copy:
    src: bundler/config
    dest: "{{ playbook_dir | dirname }}/.bundle/config"
    mode: "0644"
- name: 追加でインストールするgemパッケージの定義ファイルをコピー
  ansible.builtin.copy:
    src: Gemfile.local
    dest: "{{ playbook_dir | dirname }}/Gemfile.local"
    mode: "0644"
- name: Redmineのデータベース接続設定ファイルを作成
  ansible.builtin.template:
    src: database.yml.j2
    dest: "{{ playbook_dir | dirname }}/config/database.yml"
    mode: "0644"
- name: データベースの接続設定ファイルを生成
  ansible.builtin.template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    mode: "0644"
- name: Redmineの設定ファイルをコピー
  ansible.builtin.copy:
    src: config/configuration.yml
    dest: "{{ playbook_dir | dirname }}/config/configuration.yml"
    mode: "0644"
- name: 追加の環境設定ファイルをコピー
  ansible.builtin.copy:
    src: config/additional_environment.rb
    dest: "{{ playbook_dir | dirname }}/config/additional_environment.rb"
    mode: "0644"
- name: gemパッケージのインストール
  ansible.builtin.command:
    cmd: bundle install
    chdir: "{{ playbook_dir | dirname }}"
- name: トークンファイル生成コマンドを実行
  ansible.builtin.command:
    cmd: bundle exec rake generate_secret_token
    creates: "{{ playbook_dir | dirname }}/config/initializers/secret_token.rb"
    chdir: "{{ playbook_dir | dirname }}"
  register: generate_secret_token_result
- name: データベースのマイグレーションを実行(本体)
  ansible.builtin.command:
    cmd: bundle exec rake db:migrate
    chdir: "{{ playbook_dir | dirname }}"
- name: データベースのマイグレーションを実行(プラグイン)
  ansible.builtin.command:
    cmd: bundle exec rake redmine:plugins:migrate
    chdir: "{{ playbook_dir | dirname }}"
