---
- name: テーマディレクトリの存在確認
  ansible.builtin.stat:
    path: "{{ base_dir }}/themes"
  register: theme_dir_result
- name: テーマディレクトリ用変数を設定
  ansible.builtin.set_fact:
    redmine_theme_dir: "{{ base_dir }}/{{ 'themes' if theme_dir_result.stat.exists else 'public/themes' }}"
- name: テーマのインストール/更新
  ansible.builtin.git:
    repo: "{{ theme.value.repo }}"
    dest: "{{ redmine_theme_dir }}/{{ theme.key }}"
    version: "{{ theme.value.version | default('master') }}"
  loop: "{{ redmine_themes | dict2items }}"
  loop_control:
    loop_var: theme
    label: "{{ theme.key }}"
