---
base_dir: "{{ playbook_dir | dirname }}"

redmine_admin:
  first_name:
  last_name:
  email:
  passowrd:

## -----------
## プラグイン
## -----------
# redmine_plugins:
#   view_customize:
#     repo: https://github.com/onozaty/redmine-view-customize.git
#     version: master

## -----------
## テーマ
## -----------
# redmine_themes:
#   farend_fancy:
#     repo: https://github.com/farend/redmine_theme_farend_fancy.git
#     version: support-propshaft
#   farend_basic:
#     repo: https://github.com/farend/redmine_theme_farend_basic.git
#     version: support-propshaft
#   bleuclair:
#     repo: https://github.com/farend/redmine_theme_farend_bleuclair.git
#     version: support-propshaft

redmine_group: {}
redmine_users: {}
redmine_roles: {}
redmine_workflows: {}

redmine_user_custom_fiels: {}
redmine_project_custom_fiels: {}
redmine_issue_custom_fiels: {}

redmine_projects: {}
