---
- name: ドキュメントディレクトリを作成
  ansible.builtin.file:
    path: "{{ document_base_dir }}"
    state: directory
    mode: "0755"
- name: Import font task
  ansible.builtin.import_tasks:
    file: font.yml
- name: Import webfont task
  ansible.builtin.import_tasks:
    file: webfont.yml
- name: Import database document task
  ansible.builtin.import_tasks:
    file: database.yml
